### ISSUE TITLE
npm test not working with locally linked adapter-flat-file-db

### ISSUE THREAD

**Issue by sean-roberts** [micro-analytics/micro-analytics#34]
master tests are failing - also the ci build tag isn't reflecting this correctly

**Comment by sean-roberts** [comment]
ah, weird. Has something to do with having the db adaptor linked locally.

**Comment by sean-roberts** [comment]
Not too familiar with this problem. But it seems that because it's a linked project the file-db is not in the require path that jest is going to mock, thus it's still going to use the actual functions.

Not sure that there is a way to fix this that's very elegant...

**Comment by sean-roberts** [comment]
how is your env set up to run npm test? I keep getting lots of flak for async/await

**Comment by mxstbr** [comment]
Yeah testing changes in the adapter is a bit of a pain right now, I'm afraid...
